let heroData = [
    {
      hero_id: "105",
      name: "廉颇",
      pay_type: "10",
      new_type: "0",
      hero_type: "3",
      hero_type2: null,
      skin_name: "正义爆轰|地狱岩魂",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/105/105.jpg",
      live: "100",
      attack: "30",
      skill: "40",
      difficulty: "30"
    },
    {
      hero_id: "106",
      name: "小乔",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "恋之微风|万圣前夜|天鹅之梦|纯白花嫁|缤纷独角兽",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/106/106.jpg",
      live: "20",
      attack: "10",
      skill: "80",
      difficulty: "30"
    },
    {
      hero_id: "107",
      name: "赵云",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "4",
      skin_name: "苍天翔龙|忍●炎影|未来纪元|皇家上将|嘻哈天王|白执事|引擎之心",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/107/107.jpg",
      live: "60",
      attack: "60",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "108",
      name: "墨子",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "3",
      skin_name: "和平守望|金属风暴|龙骑士|进击墨子号",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/108/108.jpg",
      live: "50",
      attack: "40",
      skill: "50",
      difficulty: "60"
    },
    {
      hero_id: "109",
      name: "妲己",
      pay_type: "11",
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "魅惑之狐|女仆咖啡|魅力维加斯|仙境爱丽丝|少女阿狸|热情桑巴",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/109/109.jpg",
      live: "20",
      attack: "10",
      skill: "80",
      difficulty: "20"
    },
    {
      hero_id: "110",
      name: "嬴政",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "王者独尊|摇滚巨星|暗夜贵公子|优雅恋人",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/110/110.jpg",
      live: "30",
      attack: "40",
      skill: "100",
      difficulty: "60"
    },
    {
      hero_id: "111",
      name: "孙尚香",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name:
        "千金重弩|火炮千金|水果甜心|蔷薇恋人|杀手不太冷|末日机甲|沉稳之力",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/111/111.jpg",
      live: "30",
      attack: "80",
      skill: "50",
      difficulty: "60"
    },
    {
      hero_id: "112",
      name: "鲁班七号",
      pay_type: "11",
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "机关造物|木偶奇遇记|福禄兄弟|电玩小子|星空梦想",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/112/112.jpg",
      live: "10",
      attack: "100",
      skill: "30",
      difficulty: "40"
    },
    {
      hero_id: "113",
      name: "庄周",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: "3",
      skin_name: "逍遥幻梦|鲤鱼之梦|蜃楼王|云端筑梦师",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/113/113.jpg",
      live: "80",
      attack: "20",
      skill: "40",
      difficulty: "20"
    },
    {
      hero_id: "114",
      name: "刘禅",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: null,
      skin_name: "暴走机关|英喵野望|绅士熊喵",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/114/114.jpg",
      live: "70",
      attack: "30",
      skill: "50",
      difficulty: "30"
    },
    {
      hero_id: "115",
      name: "高渐离",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "叛逆吟游|金属狂潮|死亡摇滚",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/115/115.jpg",
      live: "50",
      attack: "40",
      skill: "90",
      difficulty: "40"
    },
    {
      hero_id: "116",
      name: "阿轲",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: null,
      skin_name: "信念之刃|爱心护理|暗夜猫娘|致命风华",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/116/116.jpg",
      live: "30",
      attack: "100",
      skill: "40",
      difficulty: "60"
    },
    {
      hero_id: "117",
      name: "钟无艳",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "野蛮之锤|生化警戒|王者之锤|海滩丽影",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/117/117.jpg",
      live: "70",
      attack: "50",
      skill: "70",
      difficulty: "40"
    },
    {
      hero_id: "118",
      name: "孙膑",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: "2",
      skin_name: "逆流之时|未来旅行|天使之翼|妖精王",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/118/118.jpg",
      live: "20",
      attack: "10",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "119",
      name: "扁鹊",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "6",
      skin_name: "善恶怪医|救世之瞳|化身博士|炼金王",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/119/119.jpg",
      live: "50",
      attack: "40",
      skill: "30",
      difficulty: "40"
    },
    {
      hero_id: "120",
      name: "白起",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: null,
      skin_name: "最终兵器|白色死神|狰",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/120/120.jpg",
      live: "80",
      attack: "30",
      skill: "40",
      difficulty: "40"
    },
    {
      hero_id: "121",
      name: "芈月",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "3",
      skin_name: "永恒之月|红桃皇后|大秦宣太后|重明",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/121/121.jpg",
      live: "60",
      attack: "50",
      skill: "70",
      difficulty: "50"
    },
    {
      hero_id: "123",
      name: "吕布",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "无双之魔|圣诞狂欢|天魔缭乱|末日机甲",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/123/123.jpg",
      live: "60",
      attack: "60",
      skill: "30",
      difficulty: "40"
    },
    {
      hero_id: "124",
      name: "周瑜",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "铁血都督|海军大将|真爱至上",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/124/124.jpg",
      live: "30",
      attack: "40",
      skill: "90",
      difficulty: "70"
    },
    {
      hero_id: "125",
      name: "元歌",
      pay_type: null,
      new_type: "1",
      hero_type: "4",
      hero_type2: null,
      skin_name: "无间傀儡|午夜歌剧院",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/125/125.jpg",
      live: "10",
      attack: "50",
      skill: "90",
      difficulty: "100"
    },
    {
      hero_id: "126",
      name: "夏侯惇",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "1",
      skin_name: "不羁之风|战争骑士|乘风破浪",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/126/126.jpg",
      live: "70",
      attack: "40",
      skill: "50",
      difficulty: "40"
    },
    {
      hero_id: "127",
      name: "甄姬",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "洛神降临|冰雪圆舞曲|花好人间|游园惊梦",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/127/127.jpg",
      live: "10",
      attack: "10",
      skill: "70",
      difficulty: "40"
    },
    {
      hero_id: "128",
      name: "曹操",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "鲜血枭雄|超能战警|幽灵船长|死神来了|烛龙",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/128/128.jpg",
      live: "60",
      attack: "60",
      skill: "50",
      difficulty: "40"
    },
    {
      hero_id: "129",
      name: "典韦",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "狂战士|黄金武士|穷奇",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/129/129.jpg",
      live: "60",
      attack: "60",
      skill: "30",
      difficulty: "10"
    },
    {
      hero_id: "130",
      name: "宫本武藏",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "剑圣|鬼剑武藏|未来纪元|万象初新|地狱之眼|霸王丸",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/130/130.jpg",
      live: "50",
      attack: "70",
      skill: "40",
      difficulty: "50"
    },
    {
      hero_id: "131",
      name: "李白",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: "1",
      skin_name: "青莲剑仙|范海辛|千年之狐|凤求凰",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/131/131.jpg",
      live: "40",
      attack: "70",
      skill: "60",
      difficulty: "90"
    },
    {
      hero_id: "132",
      name: "马可波罗",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "远游之枪|激情绿茵|逐梦之星",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/132/132.jpg",
      live: "30",
      attack: "60",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "133",
      name: "狄仁杰",
      pay_type: "11",
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "断案大师|锦衣卫|魔术师|超时空战士|阴阳师",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/133/133.jpg",
      live: "40",
      attack: "90",
      skill: "30",
      difficulty: "20"
    },
    {
      hero_id: "134",
      name: "达摩",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "拳僧|大发明家|拳王",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/134/134.jpg",
      live: "70",
      attack: "50",
      skill: "20",
      difficulty: "50"
    },
    {
      hero_id: "135",
      name: "项羽",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: null,
      skin_name: "霸王|帝国元帅|苍穹之光|海滩派对|职棒王牌|霸王别姬",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/135/135.jpg",
      live: "90",
      attack: "40",
      skill: "50",
      difficulty: "30"
    },
    {
      hero_id: "136",
      name: "武则天",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "女帝|东方不败|海洋之心",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/136/136.jpg",
      live: "20",
      attack: "10",
      skill: "100",
      difficulty: "60"
    },
    {
      hero_id: "139",
      name: "老夫子",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "万古长明|潮流仙人|圣诞老人|功夫老勺",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/139/139.jpg",
      live: "60",
      attack: "60",
      skill: "40",
      difficulty: "30"
    },
    {
      hero_id: "140",
      name: "关羽",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "一骑当千|天启骑士|冰锋战神|龙腾万里",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/140/140.jpg",
      live: "60",
      attack: "60",
      skill: "60",
      difficulty: "80"
    },
    {
      hero_id: "141",
      name: "貂蝉",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "4",
      skin_name: "绝世舞姬|异域舞娘|圣诞恋歌|逐梦之音|仲夏夜之梦",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/141/141.jpg",
      live: "40",
      attack: "20",
      skill: "70",
      difficulty: "60"
    },
    {
      hero_id: "142",
      name: "安琪拉",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "暗夜萝莉|玩偶对对碰|魔法小厨娘|心灵骇客",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/142/142.jpg",
      live: "40",
      attack: "10",
      skill: "80",
      difficulty: "40"
    },
    {
      hero_id: "144",
      name: "程咬金",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "1",
      skin_name: "热烈之斧|爱与正义|星际陆战队|华尔街大亨",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/144/144.jpg",
      live: "90",
      attack: "50",
      skill: "50",
      difficulty: "10"
    },
    {
      hero_id: "146",
      name: "露娜",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "2",
      skin_name: "月光之女|哥特玫瑰|绯红之刃|紫霞仙子",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/146/146.jpg",
      live: "50",
      attack: "40",
      skill: "70",
      difficulty: "90"
    },
    {
      hero_id: "148",
      name: "姜子牙",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "6",
      skin_name: "太古魔导|时尚教父",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/148/148.jpg",
      live: "10",
      attack: "20",
      skill: "70",
      difficulty: "30"
    },
    {
      hero_id: "149",
      name: "刘邦",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "6",
      skin_name: "双面君主|圣殿之光|德古拉伯爵",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/149/149.jpg",
      live: "80",
      attack: "40",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "150",
      name: "韩信",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: "1",
      skin_name: "国士无双|街头霸王|教廷特使|白龙吟|逐梦之影",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/150/150.jpg",
      live: "20",
      attack: "70",
      skill: "30",
      difficulty: "80"
    },
    {
      hero_id: "152",
      name: "王昭君",
      pay_type: "10",
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "冰雪之华|精灵公主|偶像歌手|凤凰于飞|幻想奇妙夜",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/152/152.jpg",
      live: "40",
      attack: "40",
      skill: "80",
      difficulty: "40"
    },
    {
      hero_id: "153",
      name: "兰陵王",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: null,
      skin_name: "暗影刀锋|隐刃|暗隐猎兽者",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/153/153.jpg",
      live: "40",
      attack: "80",
      skill: "40",
      difficulty: "50"
    },
    {
      hero_id: "154",
      name: "花木兰",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "4",
      skin_name: "传说之刃|剑舞者|兔女郎|水晶猎龙者|青春决赛季",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/154/154.jpg",
      live: "50",
      attack: "70",
      skill: "50",
      difficulty: "80"
    },
    {
      hero_id: "156",
      name: "张良",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "言灵之书|天堂福音|一千零一夜",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/156/156.jpg",
      live: "30",
      attack: "10",
      skill: "80",
      difficulty: "60"
    },
    {
      hero_id: "157",
      name: "不知火舞",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "4",
      skin_name: "明媚烈焰",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/157/157.jpg",
      live: "30",
      attack: "30",
      skill: "80",
      difficulty: "80"
    },
    {
      hero_id: "162",
      name: "娜可露露",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: null,
      skin_name: "鹰之守护",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/162/162.jpg",
      live: "30",
      attack: "80",
      skill: "60",
      difficulty: "40"
    },
    {
      hero_id: "163",
      name: "橘右京",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: "1",
      skin_name: "神梦一刀",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/163/163.jpg",
      live: "50",
      attack: "60",
      skill: "50",
      difficulty: "50"
    },
    {
      hero_id: "166",
      name: "亚瑟",
      pay_type: "11",
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "圣骑之力|死亡骑士|狮心王|心灵战警",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/166/166.jpg",
      live: "80",
      attack: "30",
      skill: "50",
      difficulty: "20"
    },
    {
      hero_id: "167",
      name: "孙悟空",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "4",
      skin_name: "齐天大圣|地狱火|西部大镖客|美猴王|至尊宝",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/167/167.jpg",
      live: "50",
      attack: "80",
      skill: "50",
      difficulty: "40"
    },
    {
      hero_id: "168",
      name: "牛魔",
      pay_type: "10",
      new_type: "0",
      hero_type: "3",
      hero_type2: "6",
      skin_name: "精英酋长|西部大镖客|制霸全明星",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/168/168.jpg",
      live: "70",
      attack: "40",
      skill: "50",
      difficulty: "50"
    },
    {
      hero_id: "169",
      name: "后羿",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "半神之弓|精灵王|阿尔法小队|辉光之辰",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/169/169.jpg",
      live: "30",
      attack: "80",
      skill: "40",
      difficulty: "30"
    },
    {
      hero_id: "170",
      name: "刘备",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "仁德义枪|万事如意|纽约教父|汉昭烈帝",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/170/170.jpg",
      live: "60",
      attack: "60",
      skill: "40",
      difficulty: "40"
    },
    {
      hero_id: "171",
      name: "张飞",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "6",
      skin_name: "禁血狂兽|五福同心|乱世虎臣",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/171/171.jpg",
      live: "100",
      attack: "40",
      skill: "50",
      difficulty: "60"
    },
    {
      hero_id: "173",
      name: "李元芳",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "王都密探|特种部队|黑猫爱糖果",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/173/173.jpg",
      live: "30",
      attack: "80",
      skill: "50",
      difficulty: "50"
    },
    {
      hero_id: "174",
      name: "虞姬",
      pay_type: "10",
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "森之风灵|加勒比小姐|霸王别姬|凯尔特女王",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/174/174.jpg",
      live: "40",
      attack: "80",
      skill: "50",
      difficulty: "40"
    },
    {
      hero_id: "175",
      name: "钟馗",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "1",
      skin_name: "虚灵城判|地府判官",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/175/175.jpg",
      live: "50",
      attack: "40",
      skill: "70",
      difficulty: "50"
    },
    {
      hero_id: "176",
      name: "杨玉环",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: "6",
      skin_name: "风华霓裳|霓裳曲",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/176/176.jpg",
      live: "30",
      attack: "30",
      skill: "90",
      difficulty: "50"
    },
    {
      hero_id: "177",
      name: "成吉思汗",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "苍狼末裔|维京掠夺者",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/177/177.jpg",
      live: "30",
      attack: "80",
      skill: "30",
      difficulty: "50"
    },
    {
      hero_id: "178",
      name: "杨戬",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "根源之目|埃及法老|永曜之星",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/178/178.jpg",
      live: "60",
      attack: "60",
      skill: "50",
      difficulty: "50"
    },
    {
      hero_id: "179",
      name: "女娲",
      pay_type: "10",
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "至高创世|尼罗河女神",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/179/179.jpg",
      live: "30",
      attack: "10",
      skill: "90",
      difficulty: "70"
    },
    {
      hero_id: "180",
      name: "哪吒",
      pay_type: "10",
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "桀骜炎枪|三太子|逐梦之翼",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/180/180.jpg",
      live: "80",
      attack: "30",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "182",
      name: "干将莫邪",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "淬命双剑|第七人偶",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/182/182.jpg",
      live: "40",
      attack: "30",
      skill: "80",
      difficulty: "70"
    },
    {
      hero_id: "183",
      name: "雅典娜",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "圣域余晖|战争女神|冰冠公主|神奇女侠",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/183/183.jpg",
      live: "70",
      attack: "60",
      skill: "40",
      difficulty: "60"
    },
    {
      hero_id: "184",
      name: "蔡文姬",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: null,
      skin_name: "天籁弦音|蔷薇王座|舞动绿茵",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/184/184.jpg",
      live: "50",
      attack: "10",
      skill: "80",
      difficulty: "30"
    },
    {
      hero_id: "186",
      name: "太乙真人",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: "3",
      skin_name: "炼金大师|圆桌骑士|饕餮",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/186/186.jpg",
      live: "50",
      attack: "10",
      skill: "60",
      difficulty: "70"
    },
    {
      hero_id: "187",
      name: "东皇太一",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: null,
      skin_name: "噬灭日蚀|东海龙王",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/187/187.jpg",
      live: "80",
      attack: "20",
      skill: "50",
      difficulty: "40"
    },
    {
      hero_id: "189",
      name: "鬼谷子",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: null,
      skin_name: "万物有灵|阿摩司公爵",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/189/189.jpg",
      live: "50",
      attack: "20",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "190",
      name: "诸葛亮",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "绝代智谋|星航指挥官|黄金分割率|武陵仙君",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/190/190.jpg",
      live: "30",
      attack: "10",
      skill: "80",
      difficulty: "60"
    },
    {
      hero_id: "191",
      name: "大乔",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: null,
      skin_name: "沧海之曜|伊势巫女",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/191/191.jpg",
      live: "10",
      attack: "10",
      skill: "60",
      difficulty: "60"
    },
    {
      hero_id: "192",
      name: "黄忠",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "燃魂重炮|芝加哥教父",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/192/192.jpg",
      live: "40",
      attack: "90",
      skill: "40",
      difficulty: "40"
    },
    {
      hero_id: "193",
      name: "铠",
      pay_type: null,
      new_type: "0",
      hero_type: "1",
      hero_type2: "3",
      skin_name: "破灭刃锋|龙域领主|曙光守护者",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/193/193.jpg",
      live: "70",
      attack: "70",
      skill: "40",
      difficulty: "20"
    },
    {
      hero_id: "194",
      name: "苏烈",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "1",
      skin_name: "不屈铁壁|爱与和平",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/194/194.jpg",
      live: "70",
      attack: "40",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "195",
      name: "百里玄策",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: null,
      skin_name: "嚣狂之镰|威尼斯狂欢",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/195/195.jpg",
      live: "40",
      attack: "80",
      skill: "40",
      difficulty: "100"
    },
    {
      hero_id: "196",
      name: "百里守约",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: "4",
      skin_name: "静谧之眼|绝影神枪|特工魅影",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/196/196.jpg",
      live: "20",
      attack: "70",
      skill: "40",
      difficulty: "70"
    },
    {
      hero_id: "197",
      name: "弈星",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "天元之弈|踏雪寻梅",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/197/197.jpg",
      live: "40",
      attack: "30",
      skill: "90",
      difficulty: "60"
    },
    {
      hero_id: "198",
      name: "梦奇",
      pay_type: null,
      new_type: "0",
      hero_type: "3",
      hero_type2: "2",
      skin_name: "入梦之灵|美梦成真",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/198/198.jpg",
      live: "80",
      attack: "40",
      skill: "40",
      difficulty: "40"
    },
    {
      hero_id: "199",
      name: "公孙离",
      pay_type: null,
      new_type: "0",
      hero_type: "5",
      hero_type2: null,
      skin_name: "幻舞玲珑|花间舞",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/199/199.jpg",
      live: "20",
      attack: "80",
      skill: "30",
      difficulty: "70"
    },
    {
      hero_id: "501",
      name: "明世隐",
      pay_type: null,
      new_type: "0",
      hero_type: "6",
      hero_type2: null,
      skin_name: "灵魂劫卜|占星术士",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/501/501.jpg",
      live: "60",
      attack: "30",
      skill: "50",
      difficulty: "70"
    },
    {
      hero_id: "502",
      name: "裴擒虎",
      pay_type: null,
      new_type: "0",
      hero_type: "4",
      hero_type2: "1",
      skin_name: "六合虎拳|街头霸王|梅西",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/502/502.jpg",
      live: "40",
      attack: "80",
      skill: "50",
      difficulty: "70"
    },
    {
      hero_id: "503",
      name: "狂铁",
      pay_type: "10",
      new_type: "0",
      hero_type: "1",
      hero_type2: null,
      skin_name: "战车意志|命运角斗场",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/503/503.jpg",
      live: "60",
      attack: "60",
      skill: "60",
      difficulty: "50"
    },
    {
      hero_id: "504",
      name: "米莱狄",
      pay_type: null,
      new_type: "0",
      hero_type: "2",
      hero_type2: null,
      skin_name: "筑城者|精准探案法",
      img_url: "http://game.gtimg.cn/images/yxzj/img201606/heroimg/504/504.jpg",
      live: "20",
      attack: "10",
      skill: "80",
      difficulty: "40"
    }
  ];
  
function getHero() {
      return heroData;
}
function deleteHero(hero){
      heroData = heroData.filter(o=>o!==hero);
}
function likeHero(hero){
      let tem = heroData.find(o=>o===hero);
      if (tem) tem.liked = !tem.liked;
}
function changeType(hero) {
      if (hero.hero_type === "1") return "战士";
      else if (hero.hero_type === "2") return "法师";
      else if (hero.hero_type === "3") return "坦克";
      else if (hero.hero_type === "4") return "刺客";
      else if (hero.hero_type === "5") return "射手";
      else if (hero.hero_type === "6") return "辅助";
}


var heroInfo = getHero();

function getHighestAttack(rank){
    if (rank > heroInfo.length){
      rank = heroInfo.length;
    }
    heroInfo.sort((a, b) => b.attack - a.attack);
    let highestAttack = [];
    let index = 0;
    while (index < rank){
        highestAttack.push(heroInfo[index]);
        index ++;
    }
    return highestAttack
}

function getHighestLive(rank){
    heroInfo.sort((a, b) => b.live - a.live);
    let highestLive = [];
    index = 0;
    while (index < rank){
        highestLive.push(heroInfo[index]);
        index ++;
    }
    return highestLive;
}

function searchByName(name){
    let target = heroInfo.find(a => a.name === name);
    return target;
}
